FROM golang:1.20.4 AS builder
COPY pw-pipeline/ /src/pw-pipeline
WORKDIR /src/pw-pipeline
RUN go mod tidy
WORKDIR /src/pw-pipeline/cmd/pw_ingest
RUN go build -o pw_ingest .

FROM alpine
COPY --from=builder /src/pw-pipeline/cmd/pw_ingest/pw_ingest /usr/local/bin/pw_ingest
