FROM golang:1.20.4 AS builder
COPY / /src/pw-bordercontrol
WORKDIR /src/pw-bordercontrol/pw-bordercontrol
RUN go mod tidy && \
    go build ./... && \
    go install ./...

FROM debian:bullseye-20230919-slim
COPY --from=builder /go/bin/bordercontrol /usr/local/bin/bordercontrol
ENTRYPOINT [ "/usr/local/bin/bordercontrol" ]
