FROM golang:1.21.3-bookworm AS builder
COPY / /src/pw-bordercontrol
WORKDIR /src/pw-bordercontrol/pw-bordercontrol
RUN go mod tidy && \
    go build ./... && \
    go install ./...

FROM debian:bookworm-20231009-slim
COPY --from=builder /go/bin/bordercontrol /usr/local/bin/bordercontrol
ENTRYPOINT [ "/usr/local/bin/bordercontrol" ]
