FROM golang:1.20.4 AS builder
COPY / /src/pw-bordercontrol
WORKDIR /src/pw-bordercontrol/pw-bordercontrol
RUN go mod tidy
RUN go build ./...
RUN go install ./...

FROM debian:bullseye-20230502-slim
COPY --from=builder /go/bin/bordercontrol /usr/local/bin/bordercontrol
ENTRYPOINT [ "/usr/local/bin/bordercontrol" ]
