---
version: '3.8'

networks:
  bordercontrol_feeder:
    name: bordercontrol_feeder

x-mux-common: &mux-common
  build:
    context: .
    dockerfile: Dockerfile.mux
  image: feed-multiplexer
  restart: always
  tty: true
  networks:
    - bordercontrol_feeder
  environment:
    - PW_INGEST_SINK=${PW_INGEST_SINK}
  tmpfs:
    - /run:exec,size=64M
    - /var/log

services:

  bordercontrol:
    extends:
      file: docker-compose-local.yml
      service: bordercontrol
    container_name: bordercontrol
    build:
      context: .
      dockerfile: Dockerfile.bordercontrol
    image: bordercontrol
    tty: true
    restart: always
    environment:
      - ATC_URL=${ATC_URL}
      - ATC_USER=${ATC_USER}
      - ATC_PASS=${ATC_PASS}
      - BC_CERT_FILE=${BC_CERT_FILE}
      - BC_KEY_FILE=${BC_KEY_FILE}
      - PW_INGEST_SINK=${PW_INGEST_SINK}
      - DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bordercontrol_feeder
    ports:
      - 8080:8080      # Stats Web UI (http)
      - 12345:12345    # BEAST
      - 12346:12346    # MLAT

  # feed-in image builder
  feed-in-builder:
    container_name: feed-in-builder
    build:
      context: .
      dockerfile: Dockerfile.feeder
    image: feed-in
    entrypoint: /bin/true

  # MLAT: Australia ACT
  mux-act:
    container_name: mux-act
    hostname: mux-act
    <<: *mux-common

  # MLAT: Australia NSW
  mux-nsw:
    container_name: mux-nsw
    hostname: mux-nsw
    <<: *mux-common

  # MLAT: Australia NT
  mux-nt:
    container_name: mux-nt
    hostname: mux-nt
    <<: *mux-common

  # MLAT: QLD
  mux-qld:
    container_name: mux-qld
    hostname: mux-qld
    <<: *mux-common

  # MLAT: SA
  mux-sa:
    container_name: mux-sa
    hostname: mux-sa
    <<: *mux-common

  # MLAT: TAS
  mux-tas:
    container_name: mux-tas
    hostname: mux-tas
    <<: *mux-common

  # MLAT: VIC
  mux-vic:
    container_name: mux-vic
    hostname: mux-vic
    <<: *mux-common

  # MLAT: WA
  mux-wa:
    container_name: mux-wa
    hostname: mux-wa
    <<: *mux-common

  # MLAT: NZ
  mux-nz:
    container_name: mux-nz
    hostname: mux-nz
    <<: *mux-common

  # MLAT: EU
  mux-eu:
    container_name: mux-eu
    hostname: mux-eu
    <<: *mux-common

  # MLAT: USA
  mux-us:
    container_name: mux-us
    hostname: mux-us
    <<: *mux-common

  # MLAT: ASIA
  mux-asia:
    container_name: mux-asia
    hostname: mux-asia
    <<: *mux-common
