#!/command/with-contenv bash
# shellcheck shell=bash

# Set pw_ingest binary
PW_INGEST_BIN="/usr/local/bin/pw_ingest"

# Set feeder tag/uuid
PW_INGEST_CMD=("--tag" "adsc")

# Set input
PW_INGEST_CMD+=("--fetch" "sbs1://127.0.0.1:30003")

# Set output
PW_INGEST_CMD+=("--sink" "${PW_INGEST_SINK}")

# Set ADS-C mode
PW_INGEST_CMD+=("--ads-c")

# "simple" mode
# simple   Gather ADSB data and sends it to the configured output.
PW_INGEST_CMD+=("simple")

# show version
fdmove -c 2 1 \
  "${PW_INGEST_BIN}" \
    --version |
  awk -W Interactive '{print "[pw_ingest] " $0}'

# shellcheck disable=SC2016
fdmove -c 2 1 \
  "${PW_INGEST_BIN}" \
    "${PW_INGEST_CMD[@]}" |
  awk -W Interactive '{print "[pw_ingest] " $0}'

# prevent re-launching too fast
sleep 5
