#!/usr/bin/with-contenv bash
# shellcheck shell=bash

/usr/local/bin/pw_ingest \
    --ref-lat "${FEEDER_LAT}" \
    --ref-lon "${FEEDER_LON}" \
    --tag "${FEEDER_UUID}" \
    --fetch beast://127.0.0.1:30005 \
    --sink "${PW_INGEST_SINK}" \
    simple \
    2>&1 \
    | stdbuf -o0 awk '{print "[pw_ingest] " $0}'

sleep 60