#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Set pw_ingest binary
PW_INGEST_BIN="/usr/local/bin/pw_ingest"

# Set feeder tag/uuid
PW_INGEST_CMD=("--tag" "${FEEDER_UUID}")

# Set sink
PW_INGEST_CMD+=("--fetch" "beast://127.0.0.1:30005")

# Set LAT if given
if [[ -n "${FEEDER_LAT}" ]]; then
    PW_INGEST_CMD+=("--ref-lat" "${FEEDER_LAT}")
fi

# Set LON if given
if [[ -n "${FEEDER_LON}" ]]; then
    PW_INGEST_CMD+=("--ref-lon" "${FEEDER_LON}")
fi

# "simple" mode
# simple   Gather ADSB data and sends it to the configured output.
PW_INGEST_CMD+=("simple")

# shellcheck disable=SC2016
"${PW_INGEST_BIN}" "${PW_INGEST_CMD[@]}" \
  2>&1 | stdbuf -o0 awk '{print "[pw_ingest] " $0}'

# prevent re-launching too fast
sleep 60
