#!/command/with-contenv bash
# shellcheck shell=bash

/usr/local/bin/readsb \
    --lat "${FEEDER_LAT}" \
    --lon "${FEEDER_LON}" \
    --quiet \
    --net \
    --net-bind-address 0.0.0.0 \
    --net-bi-port=12345 \
    --net-bo-port=30005 \
    --net-only
