---
name: Pull Request

on:
  # Enable manual running of action if necessary
  workflow_dispatch:
  # Test build/deploy on PRs to main/master
  pull_request:
    # Only publish on push to main branch
    # branches:
    #   - main
    # Don't trigger if it's just a documentation update
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '**.yml'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - '.dockerignore'

jobs:

  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build bordercontrol
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./Dockerfile.bordercontrol
      -
        name: Build feeder
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./Dockerfile.feeder
      -
        name: Build mux
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./Dockerfile.mux
