---
name: Push

on:
    workflow_dispatch:
    pull_request:
        paths-ignore:
            - '**.md'
            - '**.MD'
            - '**.yml'
            - 'LICENSE'
            - '.gitattributes'
            - '.gitignore'
            - '.dockerignore'
    push:
        paths-ignore:
            - '**.md'
            - '**.MD'
            - '**.yml'
            - 'LICENSE'
            - '.gitattributes'
            - '.gitignore'
            - '.dockerignore'

jobs:
    go-test:
        name: Run go tests
        runs-on: ubuntu-latest
        steps:
            -
              name: Checkout
              uses: actions/checkout@v4
            -
              name: Set up Docker
              run: |
                curl -fsSL https://get.docker.com -o /tmp/install-docker.sh
                sudo sh /tmp/install-docker.sh
            -
              name: go test
              run: |
                pushd pw-bordercontrol
                go test -v -coverprofile=../coverage.out -covermode=atomic ./...
            - 
              name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}